
export const questions: string[] = [
        "… est bavard",
        "… a tendance à critiquer les autres",
        "… travaille consciencieusement",
        "… est déprimé, cafardeux",
        "… est créatif, plein d'idées originales",
        "… est réservé",
        "… est serviable et n'est pas égoiste avec les autres",
        "… peut être parfois négligent",
        "… est 'relaxe', détendu, gère bien le stress",
        "… s'intéresse à de nombreux sujets",
        "… est plein d'énergie",
        "… commence facilement à se disputer avec les autres",
        "… est fiable dans son travail",
        "… peut être angoissé",
        "… est ingénieux, une grosse tête",
        "… communique beaucoup d'enthousiasme",
        "… est indulgent de nature",
        "… a tendance à être désorganisé",
        "… se tourmente beaucoup",
        "… a une grande imagination",
        "… a tendance à être silencieux",
        "… fait généralement confiance aux autres",
        "… a tendance à être paresseux",
        "… est quelqu'un de tempéré, pas facilement troublé",
        "… est inventif",
        "… a une forte personnalité, s'exprime avec assurance",
        "… est parfois dédaigneux, méprisant",
        "… persévère jusqu'à ce que sa tâche soit finie",
        "… peut être lunatique, d'humeur changeante",
        "… apprécie les activités artistiques et esthétiques",
        "… est quelquefois timide, inhibé",
        "… est prévenant et gentil avec presque tout le monde",
        "… est efficace dans son travail",
        "… reste calme dans les situations angoissantes",
        "… préfère un travail simple et routinier",
        "… est sociable, extraverti",
        "… est parfois impoli avec les autres",
        "… fait des projets et les poursuit",
        "… est facilement anxieux",
        "… aime réfléchir et jouer avec des idées",
        "… est peu intéressé par tout ce qui est artistique",
        "… aime coopérer avec les autres",
        "… est facilement distrait",
        "… a de bonnes connaissances en art, musique ou en littérature",
        "… cherche des histoires aux autres",
    ];