
// export const lines = [
//         [
//             {"letter": "d", "upper": 2, "below": 2},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 2, "below": 2},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//         ], 
//         [
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 2},
//             {"letter": "b", "upper": 0, "below": 1},
//         ], 
//         [
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "q", "upper": 0, "below": 2},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 1, "below": 2},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//         ], 
//         [
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 0, "below": 2},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 0, "below": 2},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 2, "below": 2},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 2},
//             {"letter": "b", "upper": 1, "below": 1},
//         ], 
//         [
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 2, "below": 2},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 0, "below": 1},
//         ], 
//         [
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "b", "upper": 0, "below": 0},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//         ], 
//         [
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 0, "below": 0},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 0, "below": 2},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 0, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//         ], 
//         [
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 2, "below": 2},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 2, "below": 2},
//             {"letter": "b", "upper": 1, "below": 1},
//         ], 
//         [
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 0, "below": 0},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 0, "below": 2},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 0, "below": 2},
//             {"letter": "b", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 0, "below": 1},
//         ], 
//         [
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 2, "below": 2},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 0, "below": 1},
//         ], 
//         [
//             {"letter": "q", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 2, "below": 2},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//         ], 
//         [
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 0, "below": 2},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 2, "below": 2},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//         ], 
//         [
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 1},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 0, "below": 2},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "q", "upper": 0, "below": 2},
//             {"letter": "d", "upper": 2, "below": 2},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 2, "below": 2},
//             {"letter": "d", "upper": 1, "below": 0},
//             {"letter": "b", "upper": 0, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 2, "below": 2},
//             {"letter": "q", "upper": 1, "below": 1},
//         ], 
//         [
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 2, "below": 0},
//             {"letter": "b", "upper": 1, "below": 2},
//             {"letter": "q", "upper": 0, "below": 0},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 2},
//             {"letter": "d", "upper": 2, "below": 1},
//             {"letter": "b", "upper": 2, "below": 1},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 0},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 2, "below": 2},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 1, "below": 1},
//             {"letter": "d", "upper": 0, "below": 0},
//             {"letter": "b", "upper": 1, "below": 1},
//             {"letter": "q", "upper": 2, "below": 0},
//             {"letter": "d", "upper": 1, "below": 1},
//             {"letter": "b", "upper": 0, "below": 2},
//             {"letter": "q", "upper": 0, "below": 1},
//             {"letter": "d", "upper": 1, "below": 2},
//             {"letter": "b", "upper": 2, "below": 0},
//             {"letter": "q", "upper": 2, "below": 1},
//             {"letter": "d", "upper": 2, "below": 2},
//             {"letter": "b", "upper": 1, "below": 0},
//             {"letter": "q", "upper": 1, "below": 0},
//             {"letter": "d", "upper": 0, "below": 1},
//         ], 
//     ]

// New version
const letters = [
    "ddpdddppdpdddddpdpdddppddddddpdpddppddddppdpddpdpdpddddpp",
    "pdppddddpdpdddpddpdpdpddpdpddddpdpdpdpddddpdpddpdpddpddpd",
    "ddddppdpdpppddpdpdpddpdpddpdppddddpddpdpdddddpdddddpddpdp",
    "ddpdddppdpdddddpdpdddppddddddpdpddppddddppdpddpdpdpddddpp",
    "pdppddddpdpdddpddpdpdpddpdpddddpdpdpdpddddpdpddpdpddpddpd",
    "ddddppdpdpppddpdpdpddpdpddpdppddddpddpdpdddddpdddddpddpdp",
    "ddpdddppdpdddddpdpdddppddddddpdpddppddddppdpddpdpdpddddpp",
    "pdppddddpdpdddpddpdpdpddpdpddddpdpdpdpddddpdpddpdpddpddpd",
    "ddddppdpdpppddpdpdpddpdpddpdppddddpddpdpdddddpdddddpddpdp",
    "ddpdddppdpdddddpdpdddppddddddpdpddppddddppdpddpdpdpddddpp",
    "pdppddddpdpdddpddpdpdpddpdpddddpdpdpdpddddpdpddpdpddpddpd",
    "ddddppdpdpppddpdpdpddpdpddpdppddddpddpdpdddddpdddddpddpdp",
    "ddpdddppdpdddddpdpdddppddddddpdpddppddddppdpddpdpdpddddpp",
    "pdppddddpdpdddpddpdpdpddpdpddddpdpdpdpddddpdpddpdpddpddpd",
]
const uppers = [
    "002220011020221120010210120112210220101220100022222120110",
    "221200212211002010100021002202020011212010220122202111111",
    "210220201020102122122110110020022212221002102212000000002",
    "002220011020221120010210120112210220101220100022222120110",
    "221200212211002010100021002202020011212010220122202111111",
    "210220201020102122122110110020022212221002102212000000002",
    "002220011020221120010210120112210220101220100022222120110",
    "221200212211002010100021002202020011212010220122202111111",
    "210220201020102122122110110020022212221002102212000000002",
    "002220011020221120010210120112210220101220100022222120110",
    "221200212211002010100021002202020011212010220122202111111",
    "210220201020102122122110110020022212221002102212000000002",
    "002220011020221120010210120112210220101220100022222120110",
    "221200212211002010100021002202020011212010220122202111111",
]
const lowers = [
    "210102211202011122201002122010202002122002122200000101101",
    "000021210202220202122101210120102211000212002100021211002",
    "202002011102120100010012211202102011001220110012212222220",
    "210102211202011122201002122010202002122002122200000101101",
    "000021210202220202122101210120102211000212002100021211001",
    "202002011102120100010012211202102011001220110012212222220",
    "210102211202011122201002122010202002122002122200000101101",
    "000021210202220202122101210120102211000212002100021211001",
    "202002011102120100010012211202102011001220110012212222220",
    "210102211202011122201002122010202002122002122200000101101",
    "000021210202220202122101210120102211000212002100021211001",
    "202002011102120100010012211202102011001220110012212222220",
    "210102211202011122201002122010202002122002122200000101101",
    "000021210202220202122101210120102211000212002100021211001",
]
export const lines = [
    [
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 1},
    ],
    [
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 2},
    ],
    [
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
    ],
    [
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 1},
    ],
    [
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
    ],
    [
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
    ],
    [
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 1},
    ],
    [
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
    ],
    [
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
    ],
    [
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 1},
    ],
    [
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
    ],
    [
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
    ],
    [
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 1},
    ],
    [
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 1},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 0, 'below': 2},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 2, 'below': 0},
        {'letter': 'd', 'upper': 2, 'below': 0},
        {'letter': 'p', 'upper': 0, 'below': 2},
        {'letter': 'd', 'upper': 2, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 2},
        {'letter': 'p', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 1},
        {'letter': 'd', 'upper': 1, 'below': 0},
        {'letter': 'p', 'upper': 1, 'below': 0},
        {'letter': 'd', 'upper': 1, 'below': 1},
    ],
]
